-- CREATE BLOCKCHAIN TABLE
CREATE TABLE IF NOT EXISTS "BLOCKCHAIN" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"PREVIOUS_HASH"	TEXT UNIQUE,
	"CURRENT_HASH"	TEXT UNIQUE,
	"LEDGER_ID"	INTEGER NOT NULL UNIQUE,
	"CREATED_ON"	TEXT,
	"CREATED_BY"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
)
-- CREATE NEW BLOCK TEMPLATE
INSERT INTO "main"."BLOCKCHAIN"
("PREVIOUS_HASH", "CURRENT_HASH", "LEDGER_ID", "CREATED_ON", "CREATED_BY")
VALUES ('3', '4', (SELECT SEQ FROM sqlite_sequence WHERE name = "BLOCKCHAIN") + 1, '1', 'SB');
-- CREATE TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS "TRANSACTIONS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"FROM"	TEXT,
	"TO"	TEXT,
	"LEDGER_ID"	INTEGER,
	"VALUE"	INTEGER,
	"SIGNATURE"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
)
-- CREATE NEW TRANSACTION TEMPLATE
INSERT INTO "main"."TRANSACTIONS"("FROM","TO","LEDGER_ID","VALUE","SIGNATURE")
 VALUES ("AA","BB",(SELECT SEQ FROM sqlite_sequence WHERE name = "BLOCKCHAIN"),20,"SBP");
-- CREATE WALLET  
CREATE TABLE IF NOT EXISTS WALLET ( 
                                PRIVATE_KEY BLOB NOT NULL UNIQUE, 
                                PUBLIC_KEY BLOB NOT NULL UNIQUE, 
                                PRIMARY KEY (PRIVATE_KEY, PUBLIC_KEY)